[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
core-utils = { path = "../../../crates/core-utils" }
db = { path = "../../../crates/db" }
